//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vs.Rules.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class keywords {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal keywords() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vs.Rules.Core.Properties.keywords", typeof(keywords).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to situatie.
        /// </summary>
        internal static string choice_situation {
            get {
                return ResourceManager.GetString("choice_situation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to berekening.
        /// </summary>
        internal static string flow {
            get {
                return ResourceManager.GetString("flow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to formule.
        /// </summary>
        internal static string formula {
            get {
                return ResourceManager.GetString("formula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to formules.
        /// </summary>
        internal static string formulas {
            get {
                return ResourceManager.GetString("formulas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stuurinformatie.
        /// </summary>
        internal static string header {
            get {
                return ResourceManager.GetString("header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to domein.
        /// </summary>
        internal static string header_domain {
            get {
                return ResourceManager.GetString("header_domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to organisatie.
        /// </summary>
        internal static string header_organization {
            get {
                return ResourceManager.GetString("header_organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jaar.
        /// </summary>
        internal static string header_period {
            get {
                return ResourceManager.GetString("header_period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bron.
        /// </summary>
        internal static string header_source {
            get {
                return ResourceManager.GetString("header_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to status.
        /// </summary>
        internal static string header_status {
            get {
                return ResourceManager.GetString("header_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to onderwerp.
        /// </summary>
        internal static string header_subject {
            get {
                return ResourceManager.GetString("header_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type.
        /// </summary>
        internal static string header_type {
            get {
                return ResourceManager.GetString("header_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to versie.
        /// </summary>
        internal static string header_version {
            get {
                return ResourceManager.GetString("header_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to situatie.
        /// </summary>
        internal static string situation {
            get {
                return ResourceManager.GetString("situation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stap.
        /// </summary>
        internal static string step_ {
            get {
                return ResourceManager.GetString("step_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to recht.
        /// </summary>
        internal static string step_break {
            get {
                return ResourceManager.GetString("step_break", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to keuze.
        /// </summary>
        internal static string step_choice {
            get {
                return ResourceManager.GetString("step_choice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to omschrijving.
        /// </summary>
        internal static string step_description {
            get {
                return ResourceManager.GetString("step_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to evalueer.
        /// </summary>
        internal static string step_evaluate {
            get {
                return ResourceManager.GetString("step_evaluate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to formule.
        /// </summary>
        internal static string step_formula {
            get {
                return ResourceManager.GetString("step_formula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to situatie.
        /// </summary>
        internal static string step_situation {
            get {
                return ResourceManager.GetString("step_situation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to waarde.
        /// </summary>
        internal static string step_value {
            get {
                return ResourceManager.GetString("step_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tabellen.
        /// </summary>
        internal static string tables {
            get {
                return ResourceManager.GetString("tables", resourceCulture);
            }
        }
    }
}
